# Generated by Django 3.0.1 on 2020-08-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='red', max_length=16),
            preserve_default=False,
        ),
    ]
