# Generated by Django 3.0.1 on 2020-08-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('red', 'red'), ('blue', 'blue')], max_length=16),
        ),
    ]
